#### general settings
#name = {model}_{dataset}_{downsample}_{scale}_{number}_{suffix}
number: !!str 001
task: classification
dataset: NWPU_RESISC45
suffix: base_demo_debug

use_tb_logger: true
data_range: center
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: NWPU_RESISC45
    mode: img2tag
    dataroot: /home/wjw/PycharmProjects/shijie/NWPU_RESISC45/tr01/

    n_workers: 0  # per GPU
    use_shuffle: true
    batch_size: 16
    input_size: 224

    color: RGB
    use_flip: true
    use_rot: true
  val:
    name: NWPU_RESISC45_Test
    mode: img2tag
    batch_size: 16
    input_size: 224
    n_workers: 0
    dataroot: /home/wjw/PycharmProjects/shijie/NWPU_RESISC45/ts09/


#### network structures
network_G:
  which_model_G: vgg16
  in_nc: 3

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 3e-5
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99

#  lr_scheme: MultiStepLR
#  niter: 100000
#  warmup_iter: -1  # no warm up
#  lr_steps: [50000, 70000, 90000, 100000]
#  lr_gamma: 0.5

  lr_scheme: CosineAnnealingLR_Restart
  niter: 100000
  warmup_iter: -1  # no warm up
  T_period: [200000, 200000]
  restarts: [200000]
  restart_weights: [1]
  eta_min: !!float 1e-7

  loss:
    label_smooth: false
    G_loss: [entropy]
    entropy_params: [cross, 1]

  manual_seed: 10
  val_freq: !!float 5e2

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e4
